[package]
name = "demon"
version = "0.1.0"
authors = ["Christopher Tarquini <ctarquini@linode.com>"]

[dependencies]
libc = "0.2.43"
nix = "0.11.0"
num-traits = "0.2"
num-derive = "0.2"

[build-dependencies]
bindgen = "0.43.0"
